Use PNPM
asyncapi/studio pull request #1088
Opened 2024-04-27 20:52 UTC by KhudaDad414

**Description**
- Following #1060 this PR migrates studio to PNPM.

2024-05-01 13:18 UTC, KhudaDad414 commented
@Amzani @Shurtu-gal. PR is ready to review.

> PS: Sorry for the long PR. It was like opening a can of worms. 😆

2024-05-02 11:32 UTC, Shurtu-gal commented
@KhudaDad414 there are some conflicts

2024-05-03 13:54 UTC, KhudaDad414 commented
@Shurtu-gal the conflicts has been resolved.

2024-05-03 13:54 UTC, KhudaDad414 commented
/ptal

2024-05-03 15:47 UTC, Shurtu-gal approved these changes

2024-05-07 13:06 UTC, KhudaDad414 commented on .github/workflows/bounty-program-commands.yml
unfortunately we can't. `.github` only supports `npm`.

if everything goes well, we can purpose our changes to `.github` repo and make sure other packages in AsyncAPI can also use `pnpm` as their package manager.

I have also remove the `nodejs` tag which makes sure that we do not get updates for the test script.

2024-05-07 13:17 UTC, Amzani requested changes
Looks good, only small change regarding this sentence in the README

```
Note: NPM v7+ is required.
```

Change to pnpm

2024-05-07 13:25 UTC, Shurtu-gal commented on .github/workflows/bounty-program-commands.yml
That's fine I was only speaking about this specific file but as it is the same with the `.github` one there is no issue. I guess I was seeing commit diff leading to this file being shown as modified.

2024-05-07 13:25 UTC, Shurtu-gal approved these changes

2024-05-07 15:37 UTC, KhudaDad414 commented
@Amzani done.

2024-05-08 08:32 UTC, Amzani approved these changes
LGTM

2024-05-08 08:32 UTC, KhudaDad414 commented
/rtm

2024-05-08 08:32 UTC, merged

2024-07-17 13:45 UTC, derberg commented
/help