feat: added tooltips for navigation bar (#193)
asyncapi/studio pull request #215
Opened 2021-12-16 10:42 UTC by boyney123

**Description**

Following #193, I added some tooltips to the navigation bar.

Let me know what you think @mcturco @magicmatatjahu

2021-12-16 11:37 UTC, magicmatatjahu requested changes
I have a problem where exactly tooltip is showed, check this:

![image](https://user-images.githubusercontent.com/20404945/146364614-d0b22d7d-c12a-4252-91a3-bce9ea053335.png)

![image](https://user-images.githubusercontent.com/20404945/146364647-6bde2e07-86b1-4503-b061-25c6ced0e6cb.png)

as you can see if I move the cursor in the nav item, but not at the icon I don't see any tooltip. It should be integrated not with icon, but with whole nav item :)

2021-12-16 11:37 UTC, magicmatatjahu commented on src/components/Sidebar.tsx
> +      <ReactTooltip effect='solid' backgroundColor='#374151' arrowColor='#374151' className="text-xs"  />
So if I wanna add tooltip in another part of Studio, e.g. in Editor, then I should copy that component and use `data-tip` attributes? 🤔  I think that component that wraps given component and add tooltip will be better, something like:

```tsx
<Tooltip content={...}>
  //...some component
</Tooltip>
```

is there any another tooltip component in the OpenSource?

2021-12-16 15:48 UTC, mcturco commented
Thanks @boyney123 for adding this!! 🎉   However, I think if we made the background of the labels fully opaque it would look a lot cleaner. I think it might be a little distracting to see things peeking through behind the labels as the text size is already rather small. What do you think?

2022-03-08 15:57 UTC, mcturco commented
@boyney123 @magicmatatjahu 

Hey guys! Was cleaning out my inbox and realized that this PR has yet to be merged. I think this is still a great feature that we should consider revisiting and merging. I think all we should do is make the tool tips fully opaque instead of transparent and integrate them with the entire button and not just the icon. Then we should definitely ship it! What do you guys think?

2022-11-21 17:17 UTC, magicmatatjahu commented
Tooltips added in the https://github.com/asyncapi/studio/pull/434 PR 

@boyney123 I hope that you don't have a problem that I'm closing this PR :)

2022-11-21 17:17 UTC, closed without merging