feat: add a modal with information about what has changed in relation to the playground.
asyncapi/studio pull request #282
Opened 2022-03-01 12:20 UTC by magicmatatjahu

… to the playground.

**Description**

Add a modal with information about what has changed in relation to the playground:
- modal opens when we have the query parameter `redirectedFrom=playground`

We need this to archive the playground repository as well as to make a redirect from playground to the studio - people should know what has changed in relation to the playground.

@derberg @alequetzalli Could you check the description of the changes?

2022-03-01 16:28 UTC, mcturco commented
Agreed that we should redirect users from the playground to the studio and archive that repo. 

I am wondering if this modal can be improved in the future to serve as an onboarding screen that delivers the new features in smaller digestible steps rather than listing them all out in one screen (things like this can seem overwhelming to users, I wonder how many will even read down the whole list?) 

Also just wondering what prompted the addition of this modal? Did someone show some confusion between playground and studio? I'm interested to see if this new modal is useful to users coming from the playground or if all of these new features are a bit more self-explanatory. 

Also curious as to what the usage will look like of this query parameter... will it only be added when redirected from the playground domain or is this something that we would maybe add to a button where first-time users of studio are more likely to click on it? Curious about how we can get this onboarding information across to more users other than just redirecting from playground without it becoming a nuisance for returning users. 

(Sorry if that was off-topic from the goals of this PR. Just kind of thinking out loud about how we could improve this modal and use it to the Studio's advantage in other ways than just one)

2022-03-02 13:14 UTC, magicmatatjahu commented
@mcturco Thanks for that comment!

> I am wondering if this modal can be improved in the future to serve as an onboarding screen that delivers the new features in smaller digestible steps rather than listing them all out in one screen (things like this can seem overwhelming to users, I wonder how many will even read down the whole list?)

Yes, we can have the "changelog" like in (e.g.) Postman app to describe changes between versions of a studio. Could you create such issue? I don't know when we will implement it but it's worth keeping in mind.

> Also just wondering what prompted the addition of this modal? Did someone show some confusion between playground and studio? I'm interested to see if this new modal is useful to users coming from the playground or if all of these new features are a bit more self-explanatory.

Some people still use the playground and when we will enable redirection from playground to the studio, some people can be confused, so we need to list all changes in relation to the playground. So that list contains new features that we don't have in playground as well changes (that same features but working in different way),

> Also curious as to what the usage will look like of this query parameter... will it only be added when redirected from the playground domain or is this something that we would maybe add to a button where first-time users of studio are more likely to click on it? Curious about how we can get this onboarding information across to more users other than just redirecting from playground without it becoming a nuisance for returning users.

Only when people will be redirected. I wonder if we should save info that someone see that modal and don't show it again even if someone will redirected from playground again 🤔  For new users we can prepare such a tutorial what is something with highlighting relevant elements, but not in this PR.

2022-03-02 15:46 UTC, magicmatatjahu commented
@derberg 

> It gives anxiety seeing so much text at first 😂

I know as a society we're going back to cuneiform writing (emoji), but I had a problem with it myself. It can be cured with a psychologist  :trollface:

2022-03-02 16:09 UTC, mcturco commented
> Can we at least collapse this list of bullet points and offer a "Show what's changed" link? A simple one, something like a summary HTML tag, nothing fancy. It gives anxiety seeing so much text at first 😂

I have to agree with @fmvilas, I think this small change could improve the modal at least within this PR. But I will definitely create an issue for working on an onboarding process in Studio so we can work on that in the future 😄

2022-03-03 09:55 UTC, magicmatatjahu commented
@mcturco @fmvilas I pushed changes:

![image](https://user-images.githubusercontent.com/20404945/156540742-edd1df53-7579-49fe-9714-7bbaf449b4c0.png)

WDYT?

2022-03-03 14:17 UTC, mcturco approved these changes
@magicmatatjahu Good idea! Definitely less overwhelming 👍  LGTM 🎉

2022-03-03 15:06 UTC, fmvilas commented
Yeah, looks great to me. Just one more suggestion. Please change the button copy to "OK" instead of "Cancel" 🙏

2022-03-03 15:09 UTC, fmvilas requested changes
And last thing. Sorry for the cluttered review 😄

2022-03-03 15:09 UTC, fmvilas commented on src/components/Modals/RedirectedModal.tsx
> +      title='Welcome in the AsyncAPI Studio!'
```suggestion
      title='Welcome to the AsyncAPI Studio!'
```

2022-03-03 15:10 UTC, fmvilas approved these changes
🚀 Ship it! :)

2022-03-03 15:14 UTC, magicmatatjahu commented
/rtm

2022-03-03 15:21 UTC, fmvilas commented
@magicmatatjahu Just realized that after closing the modal, we leave the query param in the URL so if we refresh the page we get the modal again. It would be great to remove the query param (without refreshing) once we close the modal.

2022-03-03 15:38 UTC, fmvilas approved these changes

2022-03-03 15:57 UTC, merged