chore: switch to visualiser library
asyncapi/studio pull request #342
Opened 2022-05-20 13:11 UTC by jonaslagoni

**Description**
This PR switches to the split-out visualization library.

**Related issue(s)**
fixes #261

2022-05-27 09:26 UTC, magicmatatjahu commented
@jonaslagoni We probably should "wait" with this PR, due to simple reasons:
  
- styles atm aren't good, you can see:

  ![image](https://user-images.githubusercontent.com/20404945/170671153-bf9b0b64-da47-45ac-bdad-483d0c4d4364.png)

- we don't have "title" as we have in current implementation:

  ![image](https://user-images.githubusercontent.com/20404945/170671269-1865884a-7806-450f-9cc2-61089c348cdd.png)

- we should have also "flow" animation as we have in current implementation and we should add buttons for it (in top right corner):

  ![image](https://user-images.githubusercontent.com/20404945/170671555-a9e3f546-8f7b-416e-9747-0889ff2ddc04.png)

- we should have also additional buttons as we have in bottom left corner:

  ![image](https://user-images.githubusercontent.com/20404945/170671489-3706071f-a380-4432-859a-29bd5bcfa959.png)

I think that we should wait and merge it when we will move library to AsyncAPI org and fix above problems - of course PR can be still open :)

2022-05-27 09:26 UTC, magicmatatjahu commented
/dnm

2022-09-28 15:33 UTC, jonaslagoni commented
> @jonaslagoni are you going to work on this? Do you need help?

If you could give me 48 hours a day, that would be really helpful 😆 

Current status if I am not mistaken:
- Still waiting for https://github.com/asyncapi/community/discussions/382 as we don't want to integrate it with Studio until then.
- Need to look into the styling and if anything is missing from the implementation.
- The buttons and titles that are missing are possible to add rather easily, so I just need to apply that.

Other then that, yes time is what I need 😆

2022-09-28 22:40 UTC, jonaslagoni commented
Alright, I fixed the issues you outlined @magicmatatjahu. I did not include any extra features as this is solely about switching internals with a library 🙂 

Any extra stuff I would suggest we add later.

2022-09-29 12:25 UTC, jonaslagoni commented
> we should have also "flow" animation as we have in current implementation and we should add buttons for it (in top right corner):

Okay I missed that one, that needs to be adapted.

2022-10-03 15:11 UTC, magicmatatjahu commented
@jonaslagoni Can we in some way fix styles for blocks. Look:

PR:

![image](https://user-images.githubusercontent.com/20404945/193612577-40f4a229-7b62-4c40-9d10-4c78cbd97ef6.png)

Master:

![image](https://user-images.githubusercontent.com/20404945/193612649-87efc8ed-1ce6-4900-a001-67aee1af25c5.png)

2022-10-05 11:21 UTC, jonaslagoni commented
I think those are valid improvements yes 👍

2022-10-15 17:30 UTC, jonaslagoni commented
This is what I am currently seeing in the PR. Do you see something else?

![image](https://user-images.githubusercontent.com/13396189/195999973-ab640a70-9ee6-4bcb-9aad-4d989dc270ac.png)

2022-10-15 18:35 UTC, jonaslagoni commented on package.json
> +    "react-scripts": "4.0.3",
I changed the version because of #458

2022-11-15 21:46 UTC, jonaslagoni commented
@magicmatatjahu it's all ready now, switched the library to the official AsyncAPI library.

2022-11-21 02:24 UTC, fmvilas requested changes
LGTM except this:

<img width="386" alt="Captura de Pantalla 2022-11-20 a las 18 23 17" src="https://user-images.githubusercontent.com/242119/202948209-ebdb6920-33ba-4f94-a57e-6cb80159c4fa.png">


Please, make this text more readable :)

2022-11-21 19:21 UTC, jonaslagoni commented
Done @fmvilas 🙂

2022-11-21 19:34 UTC, jonaslagoni commented
Regarding the code smell it's because of different types that will clash because each library uses different parser versions. Choose to leave it as is, let me know if you want to disable the rule for that line. 

This is until the library support the new version: https://github.com/asyncapi/EDAVisualiser/issues/10

2022-11-21 23:19 UTC, fmvilas approved these changes
🚀

2022-11-24 14:16 UTC, magicmatatjahu commented
@jonaslagoni When I switch to the visualiser I see this in console and Studio are broken:

![image](https://user-images.githubusercontent.com/20404945/203805574-301827fb-eabf-4dc4-b4ee-8fc77dff044f.png)

Which version of `react` and `react-flow` the EDAVisualiser uses? Studio now uses latest react (v18) and latest `react-flow` (v11) version.

2023-07-28 00:08 UTC, closed without merging