feat: Enable to mount local spec for docker container
asyncapi/studio pull request #433
Opened 2022-09-24 06:19 UTC by rikuson

**Description**

This is continued from https://github.com/asyncapi/studio/pull/404 .

@magicmatatjahu 

> remove provided asyncapi.yaml in this PR

If asyncapi.yaml is removed, it doesn't work on local since dev-server doesn't return 404 code in HTTP header.
dev-server returns html document even if there's no static file.
Can you just ignore `public/docs/asyncapi/asyncapi.yaml` and `public/docs/asyncapi/asyncapi.json` for deployment?

**Related issue(s)**

Resolves https://github.com/asyncapi/studio/issues/403

2023-01-23 10:06 UTC, fmvilas commented
@magicmatatjahu do you mind having a look?

2023-05-30 08:28 UTC, fmvilas approved these changes
LGTM 👍

2023-05-30 08:33 UTC, fmvilas commented
@rikuson there are errors in your code. Would you mind having a look? Apologies for the delay in the review 🙏

2023-09-26 08:47 UTC, KhudaDad414 commented
@rikuson do you need some help with this?

2023-10-01 01:15 UTC, rikuson commented
OK, I'll take a look.

2023-10-17 23:30 UTC, rikuson commented
@KhudaDad414 @fmvilas I fixed!

2023-10-17 23:43 UTC, rikuson commented
Sorry, it seems got broken after I merge master branch.

2023-10-18 01:35 UTC, rikuson commented
@KhudaDad414 @fmvilas Done.

2023-10-24 10:59 UTC, Amzani commented
@rikuson @KhudaDad414  Sonarcloud is complaining about `COPY . .`  I'm wondering why this was not triggered before. 
I see this as a common practice in multi-stage builds, I suggest to add it as an exception maybe, or explicitly copy the files.

2023-10-24 14:24 UTC, rikuson commented on apps/studio/docker-compose.yaml
Now building docker image shows error below.

```
$ docker-compose up
...
=> ERROR [builder 6/6] RUN turbo prune --scope=@asyncapi/studio --docker
Turbo error: could not resolve workspaces: We did not find a package manager specified in your root package.json. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
```

I think because it has changed into monorepo.

2023-10-24 14:26 UTC, rikuson commented on apps/studio/docker-compose.yaml
It seems not relevant with the issue.
But bring Dockerfile and docker-compose.yaml to the root, it works.
What should I do?

2023-10-24 14:36 UTC, Amzani commented on apps/studio/docker-compose.yaml
Just move both files to the root @rikuson , the sonarcloud security alert is already on the `master` branch, we'll try to fix it in an other PR, or just ignore it.

2023-10-27 13:22 UTC, Amzani commented on apps/studio/docker-compose.yaml
Any updates @rikuson ?

2023-10-28 06:31 UTC, rikuson commented on apps/studio/docker-compose.yaml
I moved both files to the root. 👍

2023-11-01 13:09 UTC, KhudaDad414 requested changes
left some comments.

2023-11-24 12:43 UTC, Amzani commented
Hi @rikuson can you take a look at this PR ? 

Thanks

2024-02-16 09:13 UTC, Amzani commented
@rikuson this PR needs some love :)

2024-02-18 18:44 UTC, rikuson commented
Sorry, I'm not motivated anymore.
I'm not gonna continue and it can be closed.

2024-03-18 05:06 UTC, closed without merging