feat: new invalid asyncapi template
asyncapi/studio pull request #524
Opened 2022-12-11 04:53 UTC by starlightknown

**Description**

- added a new asyncapi invalid document for the studio tutorial
- updated with tutorial example in index.tsx , NewFileModal.tsx
- ...

**Related issue(s)**

2022-12-12 09:24 UTC, magicmatatjahu requested changes
@starlightknown Thanks for the PR! Awesome, but we need to fix some things :) Let me know if you will have a problems.

2022-12-12 09:24 UTC, magicmatatjahu commented on src/components/Modals/NewFileModal.tsx
> +  const templates = examples.filter((template) => template.type === 'tutorial-example');
```suggestion
  const tutorials = examples.filter((template) => template.type === 'tutorial-example');
```

2022-12-12 09:24 UTC, magicmatatjahu commented on src/examples/index.tsx
> +import tutorial from './tutorials/tutorial.yml';
In the future we will have more tutorials so it's better to call it as (e.g.) `invalid` to describe purpose of the tutorial.

```suggestion
// tutorial example
import invalid from './tutorials/invalid.yml';
```

2022-12-12 09:24 UTC, magicmatatjahu commented on src/examples/index.tsx
> +    type: templateTypes.tutorial
```suggestion
    title: 'Invalid Example',
    description: () => <>An example of an invalid AsyncAPI document. This is only for educational purposes, to learn document validation.</>,
    template: invalid,
    type: templateTypes.tutorial
```

2022-12-12 09:24 UTC, magicmatatjahu commented on src/components/Modals/NewFileModal.tsx
> +  const templates = examples.filter((template) => template.type === 'tutorial-example');
Also, in this same file you need to update the React component to render tutorials:

```tsx
          <div>
            <span className="uppercase text-gray-800 text-sm underline font-bold">Tutorials</span>
            <div className="grid grid-cols-3 gap-4 py-4">
              {tutorials.map(({ title, description, template }) => {
                const isSelected = selectedTemplate.title === title;
                return <TemplateListItem title={title} description={description} isSelected={isSelected} key={title} onClick={() => setSelectedTemplate({ title, template })} />;
              })}
            </div>
          </div>
```

please paste it under 84 line :)

2022-12-12 11:15 UTC, starlightknown commented
![image](https://user-images.githubusercontent.com/74637789/207031818-73b1004b-6f42-4551-b713-84215413c91e.png)
yay its on

2022-12-12 12:31 UTC, magicmatatjahu approved these changes

2022-12-12 16:25 UTC, fmvilas approved these changes
🚀

2022-12-16 13:03 UTC, fmvilas commented
/rtm

2022-12-16 13:03 UTC, merged

2022-12-16 13:10 UTC, magicmatatjahu commented
@fmvilas https://github.com/asyncapi/website/pull/1022#issuecomment-1354032705 XD