fix: logo not visible in Studio README
asyncapi/studio pull request #658
Opened 2023-06-15 14:27 UTC by fmvilas

Studio logo is not visible on the README because the URL of the file is wrong now.

2023-06-15 14:33 UTC, KhudaDad414 submitted a review, later dismissed
Let's see if the release pipeline works 🤞

2023-06-15 16:58 UTC, magicmatatjahu approved these changes

2023-06-15 16:59 UTC, magicmatatjahu requested changes

2023-06-15 16:59 UTC, magicmatatjahu commented on apps/design-system/README.md
> +[![AsyncAPI Design System](../..//assets/github-repobanner-atom.png)](https://www.asyncapi.com)
```suggestion
[![AsyncAPI Design System](../../assets/github-repobanner-atom.png)](https://www.asyncapi.com)
```

2023-06-16 10:09 UTC, fmvilas commented on apps/design-system/README.md
> +[![AsyncAPI Design System](../..//assets/github-repobanner-atom.png)](https://www.asyncapi.com)
Good catch! Thanks!

2023-06-19 15:27 UTC, magicmatatjahu approved these changes

2023-06-19 15:41 UTC, fmvilas commented
/rtm

2023-06-19 15:42 UTC, merged