chore: [ADR-0004] use RadixUI
asyncapi/studio pull request #741
Opened 2023-07-17 08:01 UTC by Amzani

**Description**

Fixes #734
Related to #730

2023-07-17 10:01 UTC, KhudaDad414 submitted a review, later dismissed
LGTM!

2023-07-18 07:13 UTC, Amzani commented
@KhudaDad414 thanks for reviewing this, could you also review https://github.com/asyncapi/studio/pull/730 as it's linked

2023-07-18 07:54 UTC, fmvilas requested changes

2023-07-18 07:54 UTC, fmvilas commented on doc/adr/0004-use-radix-ui.md
> +In our project, we have identified the need for a set of UI components that handle not only the logical part but also the design aspects. We have evaluated existing libraries such as Radix and Headle
```suggestion
In our project, we have identified the need for a set of UI components that only handle the logical part without imposing any design aspects. We have evaluated existing libraries such as Radix and Headless UI, which provide components without implicit designs. 
```

It's actually the opposite 😄

2023-07-18 07:54 UTC, fmvilas commented on doc/adr/0004-use-radix-ui.md
> +We have concluded that using a ready-made library would restrict our freedom to customize the look and feel of the components. Additionally, these libraries integrate design elements into their compo
```suggestion
We have concluded that using a ready-made library would restrict our freedom to customize the look and feel of the components. Additionally, this kind of libraries integrate design elements into their components, making it challenging or impossible to modify them according to our specific requirements.
```

2023-07-18 15:27 UTC, KhudaDad414 approved these changes

2023-07-20 10:50 UTC, fmvilas approved these changes

2023-07-20 10:50 UTC, fmvilas commented
/au

2023-07-21 11:40 UTC, Amzani commented
/rtm

2023-07-21 11:41 UTC, merged