resolve code duplicate issue
asyncapi/studio pull request #807
Opened 2023-10-05 15:24 UTC by KhudaDad414

**Description**

- SonarClould check fails for the duplicate code in the open PRs:

This PR aims to resolve the issue.

2023-10-10 18:04 UTC, KhudaDad414 commented
@fmvilas 👁️ 🙏

2023-10-16 10:21 UTC, Amzani requested changes

2023-10-16 10:21 UTC, Amzani commented on apps/studio/src/components/Navigation.tsx
> +const V3OperationsNavigation: React.FunctionComponent<NavigationSectionProps> = ({
@KhudaDad414 we will have more and more duplicated code as we are in the transition period to V3. 
We should just add an exception in SonarCloud, and clean after ending support for V2.
Not sure if there is an other clean way to do it.

2023-10-16 10:21 UTC, Amzani commented on apps/studio/src/components/Navigation.tsx
> +const V3OperationsNavigation: React.FunctionComponent<NavigationSectionProps> = ({
Naming suggestion, I find `OperationNavigationV3` more readable than `V3OperationsNavigation`

2023-10-23 13:50 UTC, KhudaDad414 commented
#821 resolves the issue.

2023-10-23 13:50 UTC, closed without merging