Add ChipInput component
asyncapi/studio pull request #808
Opened 2023-10-05 20:55 UTC by princerajpoot20

**Related issue(s)**

Resolves #753

2023-10-06 11:00 UTC, KhudaDad414 requested changes
left some comments.

2023-10-06 11:00 UTC, KhudaDad414 commented on packages/ui/components/ChipInput.tsx
> +    <div className="flex flex-wrap items-center p-2 bg-gray-900 rounded">
based on the design, this component should have a border as well.

2023-10-06 21:19 UTC, princerajpoot20 commented
@KhudaDad414 Thankyou for the review. I have made the changes 🙂

2023-10-08 09:19 UTC, fmvilas requested changes
Left some comments.

I also noticed that if I delete the text and press delete again, it doesn't remove the last chip. I was expecting to be able to remove chips with the keyboard.

Also, I should be able to navigate through the chips using the keyboard (tab key) and remove a chip if needed (probably the delete key).

Hope that makes sense. It's looking awesome so far ♥️

2023-10-08 09:19 UTC, fmvilas commented on packages/ui/components/ChipInput.tsx
> +        defaultValue={'registr'}
I would not default it to this but an empty string. You can then create multiple cases in the design system:

1. How it looks with all the defaults
2. How it looks with some default text
3. How it looks with a custom placeholder
4. And so on...

2023-10-09 22:03 UTC, princerajpoot20 commented
@fmvilas Thank you for the review. 🙂 

> Hope that makes sense. It's looking awesome so far ♥️

Definitely makes sense. My bad. I missed these things. 
I have passed the remaining values from the design system but forgot to pass `defaultValue` from there. Instead, I just hardcoded it in the `ChipInput.tsx` 😄.

About navigating through chips, it's a great point that I missed out on. I use tab a lot to navigate. it just makes it so convenient. 
I have used `firstChipRef` to get a reference to the first chip. So, when we are in the `InputTestField` and press tab, navigation will start from the `first chip` and continue from there.

2023-10-10 09:53 UTC, fmvilas approved these changes
This is beautiful 👏 

Great stuff! 🙌

2023-10-10 09:58 UTC, KhudaDad414 approved these changes
LGMT!

2023-10-10 10:00 UTC, KhudaDad414 commented
/rtm

2023-10-10 10:01 UTC, merged