[ADR-0005] support component styling with tailwind css in design system
asyncapi/studio pull request #823
Opened 2023-10-24 10:16 UTC by KhudaDad414

I purpose we support styling components in design system with tailwind css.

2023-10-24 10:31 UTC, Amzani requested changes

2023-10-24 10:46 UTC, Amzani approved these changes
LGTM

2023-10-24 11:00 UTC, Amzani commented
/rtm

2023-10-24 11:25 UTC, KhudaDad414 commented
@Amzani can't merge without the code-owner's approval. 😄

2023-11-02 15:36 UTC, Amzani commented
/rtm

2023-11-02 15:37 UTC, merged