feat: Add v3 examples
asyncapi/studio pull request #842
Opened 2023-11-03 13:56 UTC by Amzani

Fixes https://github.com/asyncapi/studio/issues/831

2023-11-06 11:58 UTC, KhudaDad414 requested changes

2023-11-06 11:58 UTC, KhudaDad414 commented on apps/studio/src/examples/websocket-gemini.yml
>              eventId: 36902233362
`timestamp` and `timestampms` should be string in `date-time` and `time` format accordingly, according the schema mentioned.

2023-11-06 11:58 UTC, KhudaDad414 commented on apps/studio/src/examples/websocket-gemini.yml
this example is not being validated in the studio.

2023-11-15 20:27 UTC, Amzani commented on apps/studio/src/examples/websocket-gemini.yml
Fixed by updating `spec-json-schemas` dependency

2023-11-16 09:51 UTC, KhudaDad414 submitted a review, later dismissed

2023-11-24 13:01 UTC, fmvilas approved these changes

2023-11-24 13:34 UTC, Amzani commented
/rtm

2023-11-24 13:34 UTC, merged