chore: add princerajpoot20 as code owner for ds and ui
asyncapi/studio pull request #862
Opened 2023-11-28 18:57 UTC by Amzani

I suggest @princerajpoot20 as a code owner for the design system `apps/design-system/` and ui `packages/ui/` as he did major contribution to build the new components, and he is committed to support new studio vision and plans #634.

### Some contributions
- https://github.com/asyncapi/studio/pull/708
- https://github.com/asyncapi/studio/pull/710
- https://github.com/asyncapi/studio/pull/711
- https://github.com/asyncapi/studio/pull/718
- https://github.com/asyncapi/studio/pull/792
- https://github.com/asyncapi/studio/pull/808

In addition to committing to this repos he is also reviewing the work of others (e.g https://github.com/asyncapi/studio/pull/784 / https://github.com/asyncapi/studio/pull/773)

2023-11-28 19:44 UTC, fmvilas approved these changes

2023-11-28 19:44 UTC, fmvilas commented
Absolutely! 👏

2023-11-28 19:46 UTC, princerajpoot20 commented
Thank you so much for proposing me.🙇🏻‍♂️🙇🏻‍♂️ I am fully committed and will give my best. 🙂

2023-11-28 20:00 UTC, princerajpoot20 reviewed
I am not sure, but I guess `asyncapi-bot-eve` should also be added here.

2023-11-28 20:03 UTC, princerajpoot20 commented on CODEOWNERS
> +packages/ui/ @fmvilas @mcturco @KhudaDad414 @Amzani @princerajpoot20
```suggestion
apps/design-system/ @fmvilas @mcturco @KhudaDad414 @Amzani @princerajpoot20 @asyncapi-bot-eve
packages/ui/ @fmvilas @mcturco @KhudaDad414 @Amzani @princerajpoot20 @asyncapi-bot-eve
```

2023-11-29 13:01 UTC, fmvilas requested changes
@princerajpoot20 is right. The bot has to be there, I think.

2023-11-29 16:39 UTC, KhudaDad414 approved these changes
@fmvilas @princerajpoot20 but the `@asyncapi-bot-eve` is already there with full code ownership. am I missing something? 🤔 

btw, welcome aboard @princerajpoot20 ㊗️ 🥳

2023-11-29 16:52 UTC, princerajpoot20 commented
> @fmvilas @princerajpoot20 but the @asyncapi-bot-eve is already there with full code ownership. am I missing something? 🤔

@KhudaDad414 If the changes are `limited` to specific areas, such as `DS or UI`, then only the `code owners of those areas` are called for review. If the changes **include any files outside of these DS/UI segments**, then full code owners are called.

2023-11-29 16:56 UTC, KhudaDad414 commented
@princerajpoot20 the point of `asyncapi-bot-eve` is to approve bot PRs. not sure if it cares about being `called for review`. it should approve other bot PRs anyways. 🤔

2023-11-29 16:58 UTC, fmvilas commented
True. It already has full code ownership 👍

2023-11-29 16:58 UTC, fmvilas approved these changes

2023-11-29 17:05 UTC, princerajpoot20 commented
@KhudaDad414 Yes agree, it is there to approve bot PR only.

2023-11-29 17:23 UTC, Amzani commented
Welcome @princerajpoot20 😊🎉

2023-11-29 17:23 UTC, Amzani commented
/rtm

2023-11-29 17:24 UTC, merged

2023-11-29 17:44 UTC, fmvilas commented
Welcome, @princerajpoot20! 🎉 

So now that you're a code owner, you have the right to join the AsyncAPI Technical Steering Committee. If you want to join, please submit a PR updating the [MAINTAINERS.yaml](https://github.com/asyncapi/community/blob/master/MAINTAINERS.yaml). Example: https://github.com/asyncapi/community/pull/801.

2023-11-29 19:32 UTC, princerajpoot20 commented
@fmvilas @Amzani @KhudaDad414 

I wanted to say a **big thank you**🙏. Thank you for **trusting** me and having **faith** in me. **This means a lot to me.** ❤️

I am truly grateful and honored to be part of this awesome community. 🙇‍♂️ 

Your support means **a lot to me.** In this journey, I have learned and grown a lot. I will give **my best** 💯 and do **every possible thing** I can for the betterment of the **Studio** and for this **community.** 🙇‍♂️

2023-11-29 19:35 UTC, princerajpoot20 commented
> So now that you're a code owner, you have the right to join the AsyncAPI Technical Steering Committee. If you want to join, please submit a PR updating the [MAINTAINERS.yaml](https://github.com/asyncapi/community/blob/master/MAINTAINERS.yaml).

Definitely, I would love to join TSC, and be a part of this awesome community. 🚀 ❤️