added  Loading animation in studio
asyncapi/studio pull request #969
Opened 2024-02-21 11:35 UTC by riyanrathore26

feat: added animation in studio before showing error message
issue: #915 
Before adding animation 

https://github.com/asyncapi/studio/assets/97107462/afc71ca8-467d-4b65-8dd1-2d2207eb6c60

After add animation

https://github.com/asyncapi/studio/assets/97107462/9e70cea0-1eb1-4e2b-9f28-e0c568d575b8

2024-02-26 09:39 UTC, Amzani commented on apps/studio/src/components/Navigation.tsx
> +  const [loading,setloading] = useState(false);
```suggestion
  const [loading, setloading] = useState(false);
```

2024-02-26 10:08 UTC, Amzani requested changes
@riyanrathore26 could you fix linting errors as well

2024-02-27 09:47 UTC, riyanrathore26 commented
> @riyanrathore26 could you fix linting errors as well

@Amzani Can you explain in more brief?

2024-02-29 13:02 UTC, Amzani commented
/rtm

2024-02-29 13:03 UTC, Amzani approved these changes

2024-02-29 13:03 UTC, merged

2024-03-05 19:29 UTC, satishkumarsajjan reviewed
Here setTimeout is being used to create that loading state feel. Which does not solve the mentioned issue. A new approach should be used to solve the issue.